uploads = []

[[generated]]
id = "nZYdLoPZEvN9UJ75hnPcP"
uri = "file://artifacts/pos-app/assets/images/icon.png"
type = "image"
title = "pos app icon"

[[outputs]]
id = "ac2cruQ1vTpPmBUTFt5gd"
uri = "file://Al-Salik-POS-Windows-Installer.zip"
type = "unspecified"
title = "Al Salik POS — Windows Installer Project"

[[outputs]]
id = "1lXg75xOQ7UjoTx--zuZG"
uri = "file://Al-Salik-POS-Setup-1.0.0.zip"
type = "unspecified"
title = "Al Salik POS Setup 1.0.0 — Windows Installer (Extract & Run .exe)"

[[outputs]]
id = "nKE59k_ZkcSd_rn5Sfex1"
uri = "file://desktop-installer/dist/Al-Salik-POS-Setup-1.0.0.tar.gz"
type = "unspecified"
title = "Al Salik POS Setup 1.0.0 — Windows Installer (with stock fix)"

[[outputs]]
id = "KZyRIwRcE3pKB9TvipGU3"
uri = "file://desktop-installer/dist/AlSalikPOS-Installer.tar.gz"
type = "unspecified"
title = "Al Salik POS Installer (Windows) — hardened offline license + login layout"
