const colors = {
  light: {
    background: "#0F1117",
    foreground: "#F1F1F3",
    card: "#1A1D25",
    cardForeground: "#F1F1F3",
    primary: "#4F8EF7",
    primaryForeground: "#FFFFFF",
    secondary: "#22252F",
    secondaryForeground: "#C8CBDA",
    muted: "#22252F",
    mutedForeground: "#8B8FA8",
    accent: "#6C63FF",
    accentForeground: "#FFFFFF",
    destructive: "#E74C3C",
    destructiveForeground: "#FFFFFF",
    border: "#2A2D3A",
    input: "#2A2D3A",
    success: "#2ECC71",
    warning: "#F39C12",
    text: "#F1F1F3",
    tint: "#4F8EF7",
  },
  dark: {
    background: "#0F1117",
    foreground: "#F1F1F3",
    card: "#1A1D25",
    cardForeground: "#F1F1F3",
    primary: "#4F8EF7",
    primaryForeground: "#FFFFFF",
    secondary: "#22252F",
    secondaryForeground: "#C8CBDA",
    muted: "#22252F",
    mutedForeground: "#8B8FA8",
    accent: "#6C63FF",
    accentForeground: "#FFFFFF",
    destructive: "#E74C3C",
    destructiveForeground: "#FFFFFF",
    border: "#2A2D3A",
    input: "#2A2D3A",
    success: "#2ECC71",
    warning: "#F39C12",
    text: "#F1F1F3",
    tint: "#4F8EF7",
  },
  radius: 12,
};

export default colors;
